language: node_js
cache:
  npm: false
  directories:
    - ./.yarn/cache
node_js:
  - "lts/*"
  - "node"
os:
  - linux
  - osx
  - windows

# Workaround for stalled Windows build, see
# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
env:
  - YARN_GPG=no

stages:
  - name: check
  - name: test
  - name: deploy
    if: branch = master
  - name: verify
    if: branch = master

before_install:
  # Upgrade yarn 1.x: https://classic.yarnpkg.com/en/docs/install
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then use yarn 2: https://yarnpkg.com/getting-started/install
  - yarn set version latest
install: yarn
before_script: yarn run build
script: yarn test

jobs:
  include:
    - stage: check
      name: lint
      before_script: skip
      script: yarn run lint

    - stage: deploy
      name: coverage
      script: yarn run coverage
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run coverage:deploy

    # https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
    - stage: verify
      name: acceptance
      before_script: skip
      script:
        - export CYPRESS_baseUrl=https://uiengine.uix.space/test-project/
        - yarn run test-acceptance --config video=false
