language: node_js
cache:
  directories:
    - ~/.cache
node_js:
  - "lts/*"
  - "node"
os:
  - linux
  # - osx
  # - windows
stages:
  - name: check
  - name: test
  - name: deploy
    if: branch = master
  - name: verify
    if: branch = master

before_script: yarn run build
script: yarn test

jobs:
  include:
    - stage: check
      name: lint
      before_script: skip
      script: yarn run lint

    - stage: deploy
      name: coverage
      script: yarn run coverage
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run coverage:deploy

    - stage: deploy
      name: test project
      script: yarn run test-project:build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run test-project:deploy

    - stage: deploy
      name: docs
      script: yarn run docs:build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run docs:deploy

    - stage: verify
      name: acceptance
      before_script: skip
      script:
        - export CYPRESS_baseUrl=https://uiengine-sample-project.uix.space/
        - yarn run test-acceptance

before_deploy:
  - openssl aes-256-cbc -K $encrypted_226d8df99612_key -iv $encrypted_226d8df99612_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

addons:
  ssh_known_hosts:
    - uiengine.uix.space
    - uiengine-sample-project.uix.space
