language: node_js
cache:
  directories:
    - ~/.cache
node_js:
  - "lts/*"
  - "node"
os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

stages:
  - name: check
  - name: test
  - name: deploy
    if: branch = master
  - name: verify
    if: branch = master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script: yarn run build
script: yarn test

jobs:
  include:
    - stage: check
      name: lint
      before_script: skip
      script: yarn run lint

    - stage: deploy
      name: coverage
      script: yarn run coverage
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run coverage:deploy

    # https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
    - stage: verify
      name: acceptance
      before_script: skip
      script:
        - export CYPRESS_baseUrl=https://uiengine.uix.space/test-project/
        - yarn run test-acceptance --config video=false
